#!/bin/sh
exedir="/usr/lib/ghc-8.10.4/bin"
exeprog="ghc-stage2"
executablename="$exedir/$exeprog"
datadir="/usr/share"
bindir="/usr/bin"
topdir="/usr/lib/ghc-8.10.4"
executablename="$exedir/ghc"
exec "$executablename" -B"$topdir" ${1+"$@"}
