#! /bin/sh
nitrogen --restore
xrandr --output DP-0 --mode 2560x1440 --primary  --rate 144.00 --output DP-4 --mode 2560x1440 --rate 60 --right-of DP-0

bspc monitor DP-0 -d I III
bspc monitor DP-4 -d II IV


bspc config border_width         2
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
